spring.application.name=Application
server.port=9999
coach.name=Mickey Mouse
team.name=The Mouse

management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true

info.app.name="MyApplication"
info.app.details="Available in PlayStore www.playstore.com/MyApplication"
info.app.version=1.0.0

info.new.name="MyApplication"
info.new.details="Available in PlayStore www.playstore.com/MyApplication"
info.new.version=1.0.0